export const RAASI = [
  {key: 'Aries (Mesha)', value: 'Aries (Mesha)'},
  {
    key: 'Taurus (Vrishabha)',
    value: 'Taurus (Vrishabha)',
  },
  {
    key: 'Gemini (Mithuna)',
    value: 'Gemini (Mithuna)',
  },
  {key: 'Cancer (Karka)', value: 'Cancer (Karka)'},
  {key: 'Leo (Singha)', value: 'Leo (Singha)'},
  {key: 'Virgo (Kanya)', value: 'Virgo (Kanya)'},
  {key: 'Libra (Tula)', value: 'Libra (Tula)'},
  {
    key: 'Scorpio (Vrushchika)',
    value: 'Scorpio (Vrushchika)',
  },
  {
    key: 'Sagittarius (Dhanu)',
    value: 'Sagittarius (Dhanu)',
  },
  {
    key: 'Capricorn (Makara)',
    value: 'Capricorn (Makara)',
  },
  {
    key: 'Aquarius (Kumbha)',
    value: 'Aquarius (Kumbha)',
  },
  {key: 'Pisces (Meena)', value: 'Pisces (Meena)'},
];
export const MARITAL_STATUS = [
  {key: 'Single', value: 'Single'},
  {key: 'Married', value: 'Married'},
  {key: 'Divorced', value: 'Divorced'},
  {
    key: 'Awaiting divorce',
    value: 'Awaiting divorce',
  },
];
export const PHYSICAL_STATUS = [
  {key: 'Normal', value: 'Normal'},
  {
    key: 'Physically Challenged',
    value: 'Physically Challenged',
  },
  {key: "Doesn't matter", value: "Doesn't matter"},
];
export const SMOKING_HABITS = [
  {key: 'Never Smokes', value: 'Never Smokes'},
  {
    key: 'Smokes Occasionally',
    value: 'Smokes Occasionally',
  },
  {
    key: 'Smokes Regularly',
    value: 'Smokes Regularly',
  },
];
export const MOTHER_TONGUE = [
  {key: 'Angika', value: 'Angika'},
  {key: 'Arunachali', value: 'Arunachali'},
  {key: 'Assamese', value: 'Assamese'},
  {key: 'Awadhi', value: 'Awadhi'},
  {key: 'Bengali', value: 'Bengali'},
  {key: 'Bhojpuri', value: 'Bhojpuri'},
  {key: 'Brij', value: 'Brij'},
  {key: 'Bihari', value: 'Bihari'},
  {key: 'Badaga', value: 'Badaga'},
  {key: 'Chatisgarhi', value: 'Chatisgarhi'},
  {key: 'Dogri', value: 'Dogri'},
  {key: 'English', value: 'English'},
  {key: 'French', value: 'French'},
  {key: 'Garhwali', value: 'Garhwali'},
  {key: 'Garo', value: 'Garo'},
  {key: 'Gujarati', value: 'Gujarati'},
  {key: 'Haryanvi', value: 'Haryanvi'},
  {
    key: 'Himachali/Pahari',
    value: 'Himachali/Pahari',
  },
  {key: 'Hindi', value: 'Hindi'},
  {key: 'Kanauji', value: 'Kanauji'},
  {key: 'Kannada', value: 'Kannada'},
  {key: 'Kashmiri', value: 'Kashmiri'},
  {key: 'Khandesi', value: 'Khandesi'},
  {key: 'Khasi', value: 'Khasi'},
  {key: 'Konkani', value: 'Konkani'},
  {key: 'Koshali', value: 'Koshali'},
  {key: 'Kumaoni', value: 'Kumaoni'},
  {key: 'Kutchi', value: 'Kutchi'},
  {key: 'Lepcha', value: 'Lepcha'},
  {key: 'Ladacki', value: 'Ladacki'},
  {key: 'Magahi', value: 'Magahi'},
  {key: 'Maithili', value: 'Maithili'},
  {key: 'Malayalam', value: 'Malayalam'},
  {key: 'Manipuri', value: 'Manipuri'},
  {key: 'Marathi', value: 'Marathi'},
  {key: 'Marwari', value: 'Marwari'},
  {key: 'Miji', value: 'Miji'},
  {key: 'Mizo', value: 'Mizo'},
  {key: 'Monpa', value: 'Monpa'},
  {key: 'Nicobarese', value: 'Nicobarese'},
  {key: 'Nepali', value: 'Nepali'},
  {key: 'Oriya', value: 'Oriya'},
  {key: 'Punjabi', value: 'Punjabi'},
  {key: 'Rajasthani', value: 'Rajasthani'},
  {key: 'Sanskrit', value: 'Sanskrit'},
  {key: 'Santhali', value: 'Santhali'},
  {key: 'Sindhi', value: 'Sindhi'},
  {key: 'Sourashtra', value: 'Sourashtra'},
  {key: 'Tamil', value: 'Tamil'},
  {key: 'Telugu', value: 'Telugu'},
  {key: 'Tripuri', value: 'Tripuri'},
  {key: 'Tulu', value: 'Tulu'},
  {key: 'Urdu', value: 'Urdu'},
  {
    key: 'Bagri Rajasthani',
    value: 'Bagri Rajasthani',
  },
  {
    key: 'Dhundhari/Jaipuri',
    value: 'Dhundhari/Jaipuri',
  },
  {key: 'Gujari/Gojari', value: 'Gujari/Gojari'},
  {key: 'Harauti', value: 'Harauti'},
  {key: 'Lambadi', value: 'Lambadi'},
  {key: 'Malvi', value: 'Malvi'},
  {key: 'Mewari', value: 'Mewari'},
  {
    key: 'Mewati/Ahirwati',
    value: 'Mewati/Ahirwati',
  },
  {key: 'Nimadi', value: 'Nimadi'},
  {key: 'Shekhawati', value: 'Shekhawati'},
  {key: 'Wagdi', value: 'Wagdi'},
];
export const DRINKING_HABITS = [
  {key: 'Never Drink', value: 'Never Drink'},
  {
    key: 'Drink Occasionally',
    value: 'Drink Occasionally',
  },
  {
    key: 'Drink Regularly',
    value: 'Drink Regularly',
  },
];
export const EATING_HABIT = [
  {key: 'Vegetarian', value: 'Vegetarian'},
  {key: 'Eggetarian', value: 'Eggetarian'},
  {key: 'Non Vegetarian', value: 'Non Vegetarian'},
];
export const RELIGION = [
  {key: 'Hindu', value: 'Hindu'},
  {key: 'Muslim', value: 'Muslim'},
  {key: 'Muslim - Shia', value: 'Muslim - Shia'},
  {key: 'Muslim - Sunni', value: 'Muslim - Sunni'},
  {key: 'Christian', value: 'Christian'},
  {key: 'Sikh', value: 'Sikh'},
  {key: 'Jain - All', value: 'Jain - All'},
  {
    key: 'Jain - Digambar',
    value: 'Jain - Digambar',
  },
  {
    key: 'Jain - Shwetambar',
    value: 'Jain - Shwetambar',
  },
  {key: 'Parsi', value: 'Parsi'},
  {key: 'Buddhist', value: 'Buddhist'},
  {key: 'Jewish', value: 'Jewish'},
  {key: 'Inter-Religion', value: 'Inter-Religion'},
  {
    key: 'No Religious Belief',
    value: 'No Religious Belief',
  },
];
export const CASTE = [
  {key: 'Ad Dharmi', value: 'Ad Dharmi'},
  {key: 'Adi Andhra', value: 'Adi Andhra'},
  {key: 'Adi Dravida', value: 'Adi Dravida'},
  {key: 'Adi-karnataka', value: 'Adi-karnataka'},
  {key: 'Agarwal', value: 'Agarwal'},
  {key: 'Agnikula Kshatriya', value: 'Agnikula Kshatriya'},
  {key: 'Agri', value: 'Agri'},
  {key: 'Ahir Shimpi', value: 'Ahir Shimpi'},
  {key: 'Ahom', value: 'Ahom'},
  {key: 'Ambalavasi', value: 'Ambalavasi'},
  {key: 'Arekatica', value: 'Arekatica'},
  {key: 'Arora', value: 'Arora'},
  {key: 'Arunthathiyar', value: 'Arunthathiyar'},
  {key: 'Arya Vysya', value: 'Arya Vysya'},
  {key: 'Ayyaraka', value: 'Ayyaraka'},
  {key: 'Badaga', value: 'Badaga'},
  {key: 'Bagdi', value: 'Bagdi'},
  {key: 'Baidya', value: 'Baidya'},
  {key: 'Baishnab', value: 'Baishnab'},
  {key: 'Baishya', value: 'Baishya'},
  {key: 'Bajantri', value: 'Bajantri'},
  {key: 'Balija', value: 'Balija'},
  {key: 'Banayat Oriya', value: 'Banayat Oriya'},
  {key: 'Banik', value: 'Banik'},
  {key: 'Baniya', value: 'Baniya'},
  {key: 'Baniya - Bania', value: 'Baniya - Bania'},
  {key: 'Baniya - Kumuti', value: 'Baniya - Kumuti'},
  {key: 'Banjara', value: 'Banjara'},
  {key: 'Barai', value: 'Barai'},
  {key: 'Bari', value: 'Bari'},
  {key: 'Baria', value: 'Baria'},
  {key: 'Barujibi', value: 'Barujibi'},
  {key: 'Besta', value: 'Besta'},
  {key: 'Bhandari', value: 'Bhandari'},
  {key: 'Bhatia', value: 'Bhatia'},
  {key: 'Bhatraju', value: 'Bhatraju'},
  {key: 'Bhavasar Kshatriya', value: 'Bhavasar Kshatriya'},
  {key: 'Bhoi', value: 'Bhoi'},
  {key: 'Bhovi', value: 'Bhovi'},
  {key: 'Bhoyar', value: 'Bhoyar'},
  {key: 'Billava', value: 'Billava'},
  {key: 'Bishnoi/Vishnoi', value: 'Bishnoi/Vishnoi'},
  {key: 'Bondili', value: 'Bondili'},
  {key: 'Boyer', value: 'Boyer'},
  {key: 'Brahmbatt', value: 'Brahmbatt'},
  {key: 'Brahmin', value: 'Brahmin'},
  {key: 'Brahmin - Anavil', value: 'Brahmin - Anavil'},
  {key: 'Brahmin - Audichya', value: 'Brahmin - Audichya'},
  {key: 'Brahmin - Barendra', value: 'Brahmin - Barendra'},
  {key: 'Brahmin - Bhatt', value: 'Brahmin - Bhatt'},
  {key: 'Brahmin - Bhumihar', value: 'Brahmin - Bhumihar'},
  {key: 'Brahmin - Daivadnya', value: 'Brahmin - Daivadnya'},
  {key: 'Brahmin - Danua', value: 'Brahmin - Danua'},
  {key: 'Brahmin - Deshastha', value: 'Brahmin - Deshastha'},
  {key: 'Brahmin - Dhiman', value: 'Brahmin - Dhiman'},
  {key: 'Brahmin - Dravida', value: 'Brahmin - Dravida'},
  {key: 'Brahmin - Embrandiri', value: 'Brahmin - Embrandiri'},
  {key: 'Brahmin - Garhwali', value: 'Brahmin - Garhwali'},
  {key: 'Brahmin - Gaur', value: 'Brahmin - Gaur'},
  {key: 'Brahmin - Goswami', value: 'Brahmin - Goswami'},
  {key: 'Brahmin - Gujar Gaur', value: 'Brahmin - Gujar Gaur'},
  {key: 'Brahmin - Gurukkal', value: 'Brahmin - Gurukkal'},
  {key: 'Brahmin - Halua', value: 'Brahmin - Halua'},
  {key: 'Brahmin - Havyaka', value: 'Brahmin - Havyaka'},
  {key: 'Brahmin - Hoysala', value: 'Brahmin - Hoysala'},
  {key: 'Brahmin - Iyengar', value: 'Brahmin - Iyengar'},
  {key: 'Brahmin - Iyer', value: 'Brahmin - Iyer'},
  {key: 'Brahmin - Jangid', value: 'Brahmin - Jangid'},
  {key: 'Brahmin - Jhadua', value: 'Brahmin - Jhadua'},
  {key: 'Brahmin - Jyotish', value: 'Brahmin - Jyotish'},
  {key: 'Brahmin - Kanyakubj', value: 'Brahmin - Kanyakubj'},
  {key: 'Brahmin - Karhade', value: 'Brahmin - Karhade'},
  {key: 'Brahmin - Khandelwal', value: 'Brahmin - Khandelwal'},
  {key: 'Brahmin - Kokanastha', value: 'Brahmin - Kokanastha'},
  {key: 'Brahmin - Kota', value: 'Brahmin - Kota'},
  {key: 'Brahmin - Kulin', value: 'Brahmin - Kulin'},
  {key: 'Brahmin - Kumoani', value: 'Brahmin - Kumoani'},
  {key: 'Brahmin - Madhwa', value: 'Brahmin - Madhwa'},
  {key: 'Brahmin - Maithil', value: 'Brahmin - Maithil'},
  {key: 'Brahmin - Modh', value: 'Brahmin - Modh'},
  {key: 'Brahmin - Mohyal', value: 'Brahmin - Mohyal'},
  {key: 'Brahmin - Nagar', value: 'Brahmin - Nagar'},
  {key: 'Brahmin - Namboodiri', value: 'Brahmin - Namboodiri'},
  {key: 'Brahmin - Narmadiya', value: 'Brahmin - Narmadiya'},
  {key: 'Brahmin - Niyogi', value: 'Brahmin - Niyogi'},
  {key: 'Brahmin - Paliwal', value: 'Brahmin - Paliwal'},
  {key: 'Brahmin - Panda', value: 'Brahmin - Panda'},
  {key: 'Brahmin - Pandit', value: 'Brahmin - Pandit'},
  {key: 'Brahmin - Pareek', value: 'Brahmin - Pareek'},
  {key: 'Brahmin - Pushkarna', value: 'Brahmin - Pushkarna'},
  {key: 'Brahmin - Rarhi', value: 'Brahmin - Rarhi'},
  {key: 'Brahmin - Rigvedi', value: 'Brahmin - Rigvedi'},
  {key: 'Brahmin - Rudraj', value: 'Brahmin - Rudraj'},
  {key: 'Brahmin - Sakaldwipi', value: 'Brahmin - Sakaldwipi'},
  {key: 'Brahmin - Sanadya', value: 'Brahmin - Sanadya'},
  {key: 'Brahmin - Sanketi', value: 'Brahmin - Sanketi'},
  {key: 'Brahmin - Saraswat', value: 'Brahmin - Saraswat'},
  {key: 'Brahmin - Saryuparin', value: 'Brahmin - Saryuparin'},
  {key: 'Brahmin - Shivhalli', value: 'Brahmin - Shivhalli'},
  {key: 'Brahmin - Shrimali', value: 'Brahmin - Shrimali'},
  {key: 'Brahmin - Sikhwal', value: 'Brahmin - Sikhwal'},
  {key: 'Brahmin - Smartha', value: 'Brahmin - Smartha'},
  {key: 'Brahmin - Sri Vishnava', value: 'Brahmin - Sri Vishnava'},
  {key: 'Brahmin - Stanika', value: 'Brahmin - Stanika'},
  {key: 'Brahmin - Tyagi', value: 'Brahmin - Tyagi'},
  {key: 'Brahmin - Vaidiki', value: 'Brahmin - Vaidiki'},
  {key: 'Brahmin - Vaikhanasa', value: 'Brahmin - Vaikhanasa'},
  {key: 'Brahmin - Velanadu', value: 'Brahmin - Velanadu'},
  {key: 'Brahmin - Vyas', value: 'Brahmin - Vyas'},
  {key: 'Brajastha Maithil', value: 'Brajastha Maithil'},
  {key: 'Brajastha Maithil', value: 'Brajastha Maithil'},
  {key: 'Bunt (Shetty)', value: 'Bunt (Shetty)'},
  {key: 'CKP', value: 'CKP'},
  {key: 'Chalawadi and Holeya', value: 'Chalawadi and Holeya'},
  {key: 'Chambhar', value: 'Chambhar'},
  {key: 'Chandravanshi Kahar', value: 'Chandravanshi Kahar'},
  {key: 'Chasa', value: 'Chasa'},
  {key: 'Chattada Sri Vaishnava', value: 'Chattada Sri Vaishnava'},
  {key: 'Chaudary', value: 'Chaudary'},
  {key: 'Chaurasia', value: 'Chaurasia'},
  {key: 'Chennadasar', value: 'Chennadasar'},
  {key: 'Chettiar', value: 'Chettiar'},
  {key: 'Chhetri', value: 'Chhetri'},
  {key: 'Chippolu (Mera)', value: 'Chippolu (Mera)'},
  {key: 'Coorgi', value: 'Coorgi'},
  {key: 'Devadiga', value: 'Devadiga'},
  {key: 'Devandra Kula Vellalar', value: 'Devandra Kula Vellalar'},
  {key: 'Devang Koshthi', value: 'Devang Koshthi'},
  {key: 'Devanga', value: 'Devanga'},
  {key: 'Devrukhe Brahmin', value: 'Devrukhe Brahmin'},
  {key: 'Dhangar', value: 'Dhangar'},
  {key: 'Dheevara', value: 'Dheevara'},
  {key: 'Dhiman', value: 'Dhiman'},
  {key: 'Dhoba', value: 'Dhoba'},
  {key: 'Dhobi', value: 'Dhobi'},
  {key: 'Dhor / Kakkayya', value: 'Dhor / Kakkayya'},
  {key: 'Dommala', value: 'Dommala'},
  {key: 'Dumal', value: 'Dumal'},
  {key: 'Dusadh (Paswan)', value: 'Dusadh (Paswan)'},
  {key: 'Ediga', value: 'Ediga'},
  {key: 'Ezhava', value: 'Ezhava'},
  {key: 'Ezhuthachan', value: 'Ezhuthachan'},
  {key: 'Gabit', value: 'Gabit'},
  {key: 'Ganda', value: 'Ganda'},
  {key: 'Gandla', value: 'Gandla'},
  {key: 'Ganiga', value: 'Ganiga'},
  {key: 'Garhwali', value: 'Garhwali'},
  {key: 'Gatti', value: 'Gatti'},
  {key: 'Gavara', value: 'Gavara'},
  {key: 'Gawali', value: 'Gawali'},
  {key: 'Ghisadi', value: 'Ghisadi'},
  {key: 'Ghumar', value: 'Ghumar'},
  {key: 'Goala', value: 'Goala'},
  {key: 'Goan', value: 'Goan'},
  {key: 'Gomantak', value: 'Gomantak'},
  {key: 'Gondhali', value: 'Gondhali'},
  {key: 'Goud', value: 'Goud'},
  {key: 'Gounder', value: 'Gounder'},
  {key: 'Gowda', value: 'Gowda'},
  {key: 'Gramani', value: 'Gramani'},
  {key: 'Gudia', value: 'Gudia'},
  {key: 'Gujjar', value: 'Gujjar'},
  {key: 'Gupta', value: 'Gupta'},
  {key: 'Guptan', value: 'Guptan'},
  {key: 'Gurav', value: 'Gurav'},
  {key: 'Gurjar', value: 'Gurjar'},
  {key: 'Halba Koshti', value: 'Halba Koshti'},
  {key: 'Helava', value: 'Helava'},
  {key: 'Hugar (Jeer)', value: 'Hugar (Jeer)'},
  {key: 'Intercaste', value: 'Intercaste'},
  {key: 'Irani', value: 'Irani'},
  {key: 'Jaalari', value: 'Jaalari'},
  {key: 'Jaiswal', value: 'Jaiswal'},
  {key: 'Jandra', value: 'Jandra'},
  {key: 'Jangam', value: 'Jangam'},
  {key: 'Jangra - Brahmin', value: 'Jangra - Brahmin'},
  {key: 'Jat', value: 'Jat'},
  {key: 'Jatav', value: 'Jatav'},
  {key: 'Jetty/Malla', value: 'Jetty/Malla'},
  {key: 'Jogi (Nath)', value: 'Jogi (Nath)'},
  {key: 'Kachara', value: 'Kachara'},
  {key: 'Kadava Patel', value: 'Kadava Patel'},
  {key: 'Kahar', value: 'Kahar'},
  {key: 'Kaibarta', value: 'Kaibarta'},
  {key: 'Kalal', value: 'Kalal'},
  {key: 'Kalanji', value: 'Kalanji'},
  {key: 'Kalar', value: 'Kalar'},
  {key: 'Kalinga', value: 'Kalinga'},
  {key: 'Kalinga Vysya', value: 'Kalinga Vysya'},
  {key: 'Kalita', value: 'Kalita'},
  {key: 'Kalwar', value: 'Kalwar'},
  {key: 'Kamboj', value: 'Kamboj'},
  {key: 'Kamma', value: 'Kamma'},
  {key: 'Kansari', value: 'Kansari'},
  {key: 'Kapu', value: 'Kapu'},
  {key: 'Karana', value: 'Karana'},
  {key: 'Karmakar', value: 'Karmakar'},
  {key: 'Karuneegar', value: 'Karuneegar'},
  {key: 'Kasar', value: 'Kasar'},
  {key: 'Kashyap', value: 'Kashyap'},
  {key: 'Katiya', value: 'Katiya'},
  {key: 'Kavuthiyya/Ezhavathy', value: 'Kavuthiyya/Ezhavathy'},
  {key: 'Kayastha', value: 'Kayastha'},
  {key: 'Khandayat', value: 'Khandayat'},
  {key: 'Khandelwal', value: 'Khandelwal'},
  {key: 'Kharwa', value: 'Kharwa'},
  {key: 'Kharwar', value: 'Kharwar'},
  {key: 'Khatri', value: 'Khatri'},
  {key: 'Kirar', value: 'Kirar'},
  {key: 'Kokanastha Maratha', value: 'Kokanastha Maratha'},
  {key: 'Koli', value: 'Koli'},
  {key: 'Koli Mahadev', value: 'Koli Mahadev'},
  {key: 'Koli Patel', value: 'Koli Patel'},
  {key: 'Kongu Vellala Gounder', value: 'Kongu Vellala Gounder'},
  {key: 'Konkani', value: 'Konkani'},
  {key: 'Korama', value: 'Korama'},
  {key: 'Kori', value: 'Kori'},
  {key: 'Kosthi', value: 'Kosthi'},
  {key: 'Krishnavaka', value: 'Krishnavaka'},
  {key: 'Kshatriya', value: 'Kshatriya'},
  {key: 'Kudumbi', value: 'Kudumbi'},
  {key: 'Kulal', value: 'Kulal'},
  {key: 'Kulalar', value: 'Kulalar'},
  {key: 'Kulita', value: 'Kulita'},
  {key: 'Kumawat', value: 'Kumawat'},
  {key: 'Kumbhakar', value: 'Kumbhakar'},
  {key: 'Kumbhar', value: 'Kumbhar'},
  {key: 'Kumhar', value: 'Kumhar'},
  {key: 'Kummari', value: 'Kummari'},
  {key: 'Kunbi', value: 'Kunbi'},
  {key: 'Kuravan', value: 'Kuravan'},
  {key: 'Kurmi', value: 'Kurmi'},
  {key: 'Kurmi Kshatriya', value: 'Kurmi Kshatriya'},
  {key: 'Kuruba', value: 'Kuruba'},
  {key: 'Kuruhina Shetty', value: 'Kuruhina Shetty'},
  {key: 'Kurumbar', value: 'Kurumbar'},
  {key: 'Kushwaha (Koiri)', value: 'Kushwaha (Koiri)'},
  {key: 'Kutchi', value: 'Kutchi'},
  {key: 'Lambadi', value: 'Lambadi'},
  {key: 'Leva patel', value: 'Leva patel'},
  {key: 'Leva patil', value: 'Leva patil'},
  {key: 'Lingayath', value: 'Lingayath'},
  {key: 'Lodhi Rajput', value: 'Lodhi Rajput'},
  {key: 'Lohana', value: 'Lohana'},
  {key: 'Lohar', value: 'Lohar'},
  {key: 'Loniya', value: 'Loniya'},
  {key: 'Lubana', value: 'Lubana'},
  {key: 'Madiga', value: 'Madiga'},
  {key: 'Mahajan', value: 'Mahajan'},
  {key: 'Mahar', value: 'Mahar'},
  {key: 'Mahendra', value: 'Mahendra'},
  {key: 'Maheshwari', value: 'Maheshwari'},
  {key: 'Mahishya', value: 'Mahishya'},
  {key: 'Majabi', value: 'Majabi'},
  {key: 'Mala', value: 'Mala'},
  {key: 'Mali', value: 'Mali'},
  {key: 'Malla', value: 'Malla'},
  {key: 'Malviya Brahmin', value: 'Malviya Brahmin'},
  {key: 'Mangalorean', value: 'Mangalorean'},
  {key: 'Manipuri', value: 'Manipuri'},
  {key: 'Mapila', value: 'Mapila'},
  {key: 'Maratha', value: 'Maratha'},
  {key: 'Maruthuvar', value: 'Maruthuvar'},
  {key: 'Matang', value: 'Matang'},
  {key: 'Mathur', value: 'Mathur'},
  {key: 'Maurya / Shakya', value: 'Maurya / Shakya'},
  {key: 'Meena', value: 'Meena'},
  {key: 'Meenavar', value: 'Meenavar'},
  {key: 'Mehra', value: 'Mehra'},
  {key: 'Meru Darji', value: 'Meru Darji'},
  {key: 'Mochi', value: 'Mochi'},
  {key: 'Modak', value: 'Modak'},
  {key: 'Mogaveera', value: 'Mogaveera'},
  {key: 'Mudaliyar', value: 'Mudaliyar'},
  {key: 'Mudiraj', value: 'Mudiraj'},
  {key: 'Mukkulathor', value: 'Mukkulathor'},
  {key: 'Munnuru Kapu', value: 'Munnuru Kapu'},
  {key: 'Muthuraja', value: 'Muthuraja'},
  {key: 'Naagavamsam', value: 'Naagavamsam'},
  {key: 'Nadar', value: 'Nadar'},
  {key: 'Nagaralu', value: 'Nagaralu'},
  {key: 'Nai', value: 'Nai'},
  {key: 'Naicker', value: 'Naicker'},
  {key: 'Naidu', value: 'Naidu'},
  {key: 'Naik', value: 'Naik'},
  {key: 'Nair', value: 'Nair'},
  {key: 'Nambiar', value: 'Nambiar'},
  {key: 'Namosudra', value: 'Namosudra'},
  {key: 'Napit', value: 'Napit'},
  {key: 'Nayaka', value: 'Nayaka'},
  {key: 'Neeli', value: 'Neeli'},
  {key: 'Nepali', value: 'Nepali'},
  {key: 'Nhavi', value: 'Nhavi'},
  {key: 'Oswal', value: 'Oswal'},
  {key: 'Otari', value: 'Otari'},
  {key: 'Padmasali', value: 'Padmasali'},
  {key: 'Pal', value: 'Pal'},
  {key: 'Panchal', value: 'Panchal'},
  {key: 'Pandaram', value: 'Pandaram'},
  {key: 'Panicker', value: 'Panicker'},
  {key: 'Parkava Kulam', value: 'Parkava Kulam'},
  {key: 'Parsi', value: 'Parsi'},
  {key: 'Partraj', value: 'Partraj'},
  {key: 'Pasi', value: 'Pasi'},
  {key: 'Patel', value: 'Patel'},
  {key: 'Pathare Prabhu', value: 'Pathare Prabhu'},
  {key: 'Patnaick', value: 'Patnaick'},
  {key: 'Patra', value: 'Patra'},
  {key: 'Perika', value: 'Perika'},
  {key: 'Pillai', value: 'Pillai'},
  {key: 'Poosala', value: 'Poosala'},
  {key: 'Porwal', value: 'Porwal'},
  {key: 'Prajapati', value: 'Prajapati'},
  {key: 'Raigar', value: 'Raigar'},
  {key: 'Rajaka', value: 'Rajaka'},
  {key: 'Rajastani', value: 'Rajastani'},
  {key: 'Rajbhar', value: 'Rajbhar'},
  {key: 'Rajbonshi', value: 'Rajbonshi'},
  {key: 'Rajpurohit', value: 'Rajpurohit'},
  {key: 'Rajput', value: 'Rajput'},
  {key: 'Ramanandi', value: 'Ramanandi'},
  {key: 'Ramdasia', value: 'Ramdasia'},
  {key: 'Ramgariah', value: 'Ramgariah'},
  {key: 'Ramoshi', value: 'Ramoshi'},
  {key: 'Ravidasia', value: 'Ravidasia'},
  {key: 'Rawat', value: 'Rawat'},
  {key: 'Reddy', value: 'Reddy'},
  {key: 'Relli', value: 'Relli'},
  {key: 'Ror', value: 'Ror'},
  {key: 'SC', value: 'SC'},
  {key: 'SKP', value: 'SKP'},
  {key: 'ST', value: 'ST'},
  {key: 'Sadgope', value: 'Sadgope'},
  {key: 'Saha', value: 'Saha'},
  {key: 'Sahu', value: 'Sahu'},
  {key: 'Saini', value: 'Saini'},
  {key: 'Saliya', value: 'Saliya'},
  {key: 'Sathwara', value: 'Sathwara'},
  {key: 'Savji', value: 'Savji'},
  {key: 'Senai Thalaivar', value: 'Senai Thalaivar'},
  {key: 'Senguntha Mudaliyar', value: 'Senguntha Mudaliyar'},
  {key: 'Settibalija', value: 'Settibalija'},
  {key: 'Shimpi', value: 'Shimpi'},
  {key: 'Sindhi', value: 'Sindhi'},
  {key: 'Sindhi-Amil', value: 'Sindhi-Amil'},
  {key: 'Sindhi-Baibhand', value: 'Sindhi-Baibhand'},
  {key: 'Sindhi-Bhanusali', value: 'Sindhi-Bhanusali'},
  {key: 'Sindhi-Bhatia', value: 'Sindhi-Bhatia'},
  {key: 'Sindhi-Chhapru', value: 'Sindhi-Chhapru'},
  {key: 'Sindhi-Dadu', value: 'Sindhi-Dadu'},
  {key: 'Sindhi-Hyderabadi', value: 'Sindhi-Hyderabadi'},
  {key: 'Sindhi-Larai', value: 'Sindhi-Larai'},
  {key: 'Sindhi-Larkana', value: 'Sindhi-Larkana'},
  {key: 'Sindhi-Lohana', value: 'Sindhi-Lohana'},
  {key: 'Sindhi-Rohiri', value: 'Sindhi-Rohiri'},
  {key: 'Sindhi-Sahiti', value: 'Sindhi-Sahiti'},
  {key: 'Sindhi-Sakkhar', value: 'Sindhi-Sakkhar'},
  {key: 'Sindhi-Sehwani', value: 'Sindhi-Sehwani'},
  {key: 'Sindhi-Shikarpuri', value: 'Sindhi-Shikarpuri'},
  {key: 'Sindhi-Thatai', value: 'Sindhi-Thatai'},
  {key: 'Sonar', value: 'Sonar'},
  {key: 'Soni', value: 'Soni'},
  {key: 'Sourashtra', value: 'Sourashtra'},
  {key: 'Sozhiya Vellalar', value: 'Sozhiya Vellalar'},
  {key: 'Srisayana', value: 'Srisayana'},
  {key: 'Sugali (Naika)', value: 'Sugali (Naika)'},
  {key: 'Sunari', value: 'Sunari'},
  {key: 'Sundhi', value: 'Sundhi'},
  {key: 'Surya Balija', value: 'Surya Balija'},
  {key: 'Suthar', value: 'Suthar'},
  {key: 'Swakula Sali', value: 'Swakula Sali'},
  {key: 'Tamboli', value: 'Tamboli'},
  {key: 'Tanti', value: 'Tanti'},
  {key: 'Tantubai', value: 'Tantubai'},
  {key: 'Telaga', value: 'Telaga'},
  {key: 'Teli', value: 'Teli'},
  {key: 'Thakkar', value: 'Thakkar'},
  {key: 'Thakore', value: 'Thakore'},
  {key: 'Thakur', value: 'Thakur'},
  {key: 'Thigala', value: 'Thigala'},
  {key: 'Thiyya', value: 'Thiyya'},
  {key: 'Tili', value: 'Tili'},
  {key: 'Togata', value: 'Togata'},
  {key: 'Tonk Kshatriya', value: 'Tonk Kshatriya'},
  {key: 'Turupu Kapu', value: 'Turupu Kapu'},
  {key: 'Uppara', value: 'Uppara'},
  {key: 'Urali Gounder', value: 'Urali Gounder'},
  {key: 'Urs', value: 'Urs'},
  {key: 'Vada Balija', value: 'Vada Balija'},
  {key: 'Vaddera', value: 'Vaddera'},
  {key: 'Vaish', value: 'Vaish'},
  {key: 'Vaishnav', value: 'Vaishnav'},
  {key: 'Vaishnava', value: 'Vaishnava'},
  {key: 'Vaishya', value: 'Vaishya'},
  {key: 'Vaishya Vani', value: 'Vaishya Vani'},
  {key: 'Valluvan', value: 'Valluvan'},
  {key: 'Valmiki', value: 'Valmiki'},
  {key: 'Vania', value: 'Vania'},
  {key: 'Vanika Vyshya', value: 'Vanika Vyshya'},
  {key: 'Vaniya', value: 'Vaniya'},
  {key: 'Vanjara', value: 'Vanjara'},
  {key: 'Vanjari', value: 'Vanjari'},
  {key: 'Vankar', value: 'Vankar'},
  {key: 'Vannar', value: 'Vannar'},
  {key: 'Vannia Kula Kshatriyar', value: 'Vannia Kula Kshatriyar'},
  {key: 'Variar', value: 'Variar'},
  {key: 'Varshney', value: 'Varshney'},
  {key: 'Veera Saivam', value: 'Veera Saivam'},
  {key: 'Velaan', value: 'Velaan'},
  {key: 'Velama', value: 'Velama'},
  {key: 'Vellalar', value: 'Vellalar'},
  {key: 'Veluthedathu Nair', value: 'Veluthedathu Nair'},
  {key: 'Vettuva Gounder', value: 'Vettuva Gounder'},
  {key: 'Vilakkithala Nair', value: 'Vilakkithala Nair'},
  {key: 'Viswabrahmin', value: 'Viswabrahmin'},
  {key: 'Viswakarma', value: 'Viswakarma'},
  {key: 'Vokkaliga', value: 'Vokkaliga'},
  {key: 'Vysya', value: 'Vysya'},
  {key: 'Yadav', value: 'Yadav'},
  {key: 'Yellapu', value: 'Yellapu'},
  {key: 'Others', value: 'Others'},
  {key: 'Muslim - Ansari', value: 'Muslim - Ansari'},
  {key: 'Muslim - Arain', value: 'Muslim - Arain'},
  {key: 'Muslim - Awan', value: 'Muslim - Awan'},
  {key: 'Alavi - Bohra', value: 'Alavi - Bohra'},
  {key: 'Muslim - Dakhini', value: 'Muslim - Dakhini'},
  {key: 'Muslim - Dudekula', value: 'Muslim - Dudekula'},
  {key: 'Muslim - Hanafi', value: 'Muslim - Hanafi'},
  {key: 'Muslim - Jat', value: 'Muslim - Jat'},
  {key: 'Muslim - Khoja', value: 'Muslim - Khoja'},
  {key: 'Muslim - Labbay', value: 'Muslim - Labbay'},
  {key: 'Muslim - Malik', value: 'Muslim - Malik'},
  {key: 'Muslim - Mappila', value: 'Muslim - Mappila'},
  {key: 'Muslim - Marakayar', value: 'Muslim - Marakayar'},
  {key: 'Muslim - Memon', value: 'Muslim - Memon'},
  {key: 'Muslim - Mughal', value: 'Muslim - Mughal'},
  {key: 'Muslim - Pathan', value: 'Muslim - Pathan'},
  {key: 'Muslim - Qureshi', value: 'Muslim - Qureshi'},
  {key: 'Muslim - Rajput', value: 'Muslim - Rajput'},
  {key: 'Muslim - Rowther', value: 'Muslim - Rowther'},
  {key: 'Muslim - Shafi', value: 'Muslim - Shafi'},
  {key: 'Muslim - Sheikh', value: 'Muslim - Sheikh'},
  {key: 'Muslim - Siddiqui', value: 'Muslim - Siddiqui'},
  {key: 'Muslim - Syed', value: 'Muslim - Syed'},
  {key: 'Muslim - UnSpecified', value: 'Muslim - UnSpecified'},
  {key: 'Others', value: 'Others'},
  {
    key: "Shia Isma'ilis (Seveners)",
    value: "Shia Isma'ilis (Seveners)",
  },
  {
    key: 'Shia Ithna Asharis (Twelvers)',
    value: 'Shia Ithna Asharis (Twelvers)',
  },
  {key: 'Shia Zaidis (Fivers)', value: 'Shia Zaidis (Fivers)'},
  {key: 'Muslim - Ansari', value: 'Muslim - Ansari'},
  {key: 'Muslim - Arain', value: 'Muslim - Arain'},
  {key: 'Muslim - Awan', value: 'Muslim - Awan'},
  {key: 'Alavi - Bohra', value: 'Alavi - Bohra'},
  {key: 'Muslim - Dakhini', value: 'Muslim - Dakhini'},
  {key: 'Muslim - Dudekula', value: 'Muslim - Dudekula'},
  {key: 'Muslim - Hanafi', value: 'Muslim - Hanafi'},
  {key: 'Muslim - Jat', value: 'Muslim - Jat'},
  {key: 'Muslim - Khoja', value: 'Muslim - Khoja'},
  {key: 'Muslim - Labbay', value: 'Muslim - Labbay'},
  {key: 'Muslim - Malik', value: 'Muslim - Malik'},
  {key: 'Muslim - Mappila', value: 'Muslim - Mappila'},
  {key: 'Muslim - Marakayar', value: 'Muslim - Marakayar'},
  {key: 'Muslim - Memon', value: 'Muslim - Memon'},
  {key: 'Muslim - Mughal', value: 'Muslim - Mughal'},
  {key: 'Muslim - Pathan', value: 'Muslim - Pathan'},
  {key: 'Muslim - Qureshi', value: 'Muslim - Qureshi'},
  {key: 'Muslim - Rajput', value: 'Muslim - Rajput'},
  {key: 'Muslim - Rowther', value: 'Muslim - Rowther'},
  {key: 'Muslim - Shafi', value: 'Muslim - Shafi'},
  {key: 'Muslim - Sheikh', value: 'Muslim - Sheikh'},
  {key: 'Muslim - Siddiqui', value: 'Muslim - Siddiqui'},
  {key: 'Muslim - Syed', value: 'Muslim - Syed'},
  {key: 'Muslim - UnSpecified', value: 'Muslim - UnSpecified'},
  {key: 'Others', value: 'Others'},
  {key: 'Sunni Hanabali', value: 'Sunni Hanabali'},
  {key: 'Sunni Hanafi', value: 'Sunni Hanafi'},
  {key: 'Sunni Maliki', value: 'Sunni Maliki'},
  {key: 'Sunni Shafii', value: 'Sunni Shafii'},
  {key: 'Muslim - Ansari', value: 'Muslim - Ansari'},
  {key: 'Muslim - Arain', value: 'Muslim - Arain'},
  {key: 'Muslim - Awan', value: 'Muslim - Awan'},
  {key: 'Alavi - Bohra', value: 'Alavi - Bohra'},
  {key: 'Muslim - Dakhini', value: 'Muslim - Dakhini'},
  {key: 'Muslim - Dudekula', value: 'Muslim - Dudekula'},
  {key: 'Muslim - Hanafi', value: 'Muslim - Hanafi'},
  {key: 'Muslim - Jat', value: 'Muslim - Jat'},
  {key: 'Muslim - Khoja', value: 'Muslim - Khoja'},
  {key: 'Muslim - Labbay', value: 'Muslim - Labbay'},
  {key: 'Muslim - Malik', value: 'Muslim - Malik'},
  {key: 'Muslim - Mappila', value: 'Muslim - Mappila'},
  {key: 'Muslim - Marakayar', value: 'Muslim - Marakayar'},
  {key: 'Muslim - Memon', value: 'Muslim - Memon'},
  {key: 'Muslim - Mughal', value: 'Muslim - Mughal'},
  {key: 'Muslim - Pathan', value: 'Muslim - Pathan'},
  {key: 'Muslim - Qureshi', value: 'Muslim - Qureshi'},
  {key: 'Muslim - Rajput', value: 'Muslim - Rajput'},
  {key: 'Muslim - Rowther', value: 'Muslim - Rowther'},
  {key: 'Muslim - Shafi', value: 'Muslim - Shafi'},
  {key: 'Muslim - Sheikh', value: 'Muslim - Sheikh'},
  {key: 'Muslim - Siddiqui', value: 'Muslim - Siddiqui'},
  {key: 'Muslim - Syed', value: 'Muslim - Syed'},
  {key: 'Muslim - UnSpecified', value: 'Muslim - UnSpecified'},
  {key: 'Others', value: 'Others'},
  {key: 'Adventist', value: 'Adventist'},
  {key: 'Anglican / Episcopal', value: 'Anglican / Episcopal'},
  {key: 'Apostolic', value: 'Apostolic'},
  {key: 'Assyrian', value: 'Assyrian'},
  {key: 'Assembly of God (AG)', value: 'Assembly of God (AG)'},
  {key: 'Baptist', value: 'Baptist'},
  {key: 'Calvinist', value: 'Calvinist'},
  {key: 'Christian - Born Again', value: 'Christian - Born Again'},
  {key: 'Christian - Bretheren', value: 'Christian - Bretheren'},
  {
    key: 'Christian - Church of South India',
    value: 'Christian - Church of South India',
  },
  {key: 'Christian - Evangelist', value: 'Christian - Evangelist'},
  {key: 'Christian - Jacobite', value: 'Christian - Jacobite'},
  {key: 'Christian - Knanaya', value: 'Christian - Knanaya'},
  {
    key: 'Christian - Knanaya Catholic',
    value: 'Christian - Knanaya Catholic',
  },
  {
    key: 'Christian - Knanaya Jacobite',
    value: 'Christian - Knanaya Jacobite',
  },
  {
    key: 'Christian - Latin Catholic',
    value: 'Christian - Latin Catholic',
  },
  {key: 'Christian - Malankara', value: 'Christian - Malankara'},
  {key: 'Christian - Marthoma', value: 'Christian - Marthoma'},
  {key: 'Christian - Pentacost', value: 'Christian - Pentacost'},
  {
    key: 'Christian - Roman Catholic',
    value: 'Christian - Roman Catholic',
  },
  {
    key: 'Christian - Syrian Catholic',
    value: 'Christian - Syrian Catholic',
  },
  {
    key: 'Christian - Syrian Jacobite',
    value: 'Christian - Syrian Jacobite',
  },
  {
    key: 'Christian - Syrian Orthodox',
    value: 'Christian - Syrian Orthodox',
  },
  {
    key: 'Christian - Syro Malabar',
    value: 'Christian - Syro Malabar',
  },
  {key: 'Christian - Unspecified', value: 'Christian - Unspecified'},
  {key: 'Church of God', value: 'Church of God'},
  {key: 'Church of Christ', value: 'Church of Christ'},
  {key: 'Church of North India', value: 'Church of North India'},
  {key: 'Congregational', value: 'Congregational'},
  {key: 'East Indian Catholic', value: 'East Indian Catholic'},
  {key: "Jehovah's Witnesses", value: "Jehovah's Witnesses"},
  {key: 'Latter day saints', value: 'Latter day saints'},
  {key: 'Lutheran', value: 'Lutheran'},
  {key: 'Melkite', value: 'Melkite'},
  {
    key: 'Malabar Independent Syrian Church',
    value: 'Malabar Independent Syrian Church',
  },
  {key: 'Mennonite', value: 'Mennonite'},
  {key: 'Methodist', value: 'Methodist'},
  {key: 'Moravian', value: 'Moravian'},
  {key: 'Protestant', value: 'Protestant'},
  {key: 'Presbyterian', value: 'Presbyterian'},
  {key: 'Seventh-day Adventist', value: 'Seventh-day Adventist'},
  {key: 'Reformed Baptist', value: 'Reformed Baptist'},
  {key: 'Reformed Presbyterian', value: 'Reformed Presbyterian'},
  {key: 'Knanaya', value: 'Knanaya'},
  {key: 'Knanaya Catholic', value: 'Knanaya Catholic'},
  {key: 'Knanaya Jacobite', value: 'Knanaya Jacobite'},
  {key: 'St. Thomas Evangelical', value: 'St. Thomas Evangelical'},
  {key: 'Syrian Jacobite', value: 'Syrian Jacobite'},
  {key: 'Syrian Orthodox', value: 'Syrian Orthodox'},
  {key: 'Others', value: 'Others'},
  {key: 'Sikh - Ahluwalia', value: 'Sikh - Ahluwalia'},
  {key: 'Sikh - Arora', value: 'Sikh - Arora'},
  {key: 'Sikh - Bhatia', value: 'Sikh - Bhatia'},
  {key: 'Sikh - Ghumar', value: 'Sikh - Ghumar'},
  {key: 'Sikh - Intercaste', value: 'Sikh - Intercaste'},
  {key: 'Sikh - Jat', value: 'Sikh - Jat'},
  {key: 'Sikh - Kamboj', value: 'Sikh - Kamboj'},
  {key: 'Sikh - Khatri', value: 'Sikh - Khatri'},
  {key: 'Sikh - Kshatriya', value: 'Sikh - Kshatriya'},
  {key: 'Sikh - Lubana', value: 'Sikh - Lubana'},
  {key: 'Sikh - Majabi', value: 'Sikh - Majabi'},
  {key: 'Sikh - Nai', value: 'Sikh - Nai'},
  {key: 'Sikh - No Bar', value: 'Sikh - No Bar'},
  {key: 'Sikh - Rajput', value: 'Sikh - Rajput'},
  {key: 'Sikh - Ramdasia', value: 'Sikh - Ramdasia'},
  {key: 'Sikh - Ramgharia', value: 'Sikh - Ramgharia'},
  {key: 'Sikh - Saini', value: 'Sikh - Saini'},
  {key: 'Sikh - Ravidasia', value: 'Sikh - Ravidasia'},
  {key: 'Sikh - Bhatra', value: 'Sikh - Bhatra'},
  {key: 'Sikh - Tonk Kshatriya', value: 'Sikh - Tonk Kshatriya'},
  {key: 'Sikh - Unspecified', value: 'Sikh - Unspecified'},
  {key: 'Others', value: 'Others'},
  {key: 'Jain - Agarwal', value: 'Jain - Agarwal'},
  {key: 'Jain - Bania', value: 'Jain - Bania'},
  {key: 'Jain - Intercaste', value: 'Jain - Intercaste'},
  {key: 'Jain - Jaiswal', value: 'Jain - Jaiswal'},
  {key: 'Jain - Khandelwal', value: 'Jain - Khandelwal'},
  {key: 'Jain - Kutchi', value: 'Jain - Kutchi'},
  {key: 'Jain - No Bar', value: 'Jain - No Bar'},
  {key: 'Jain - Oswal', value: 'Jain - Oswal'},
  {key: 'Jain - Porwal', value: 'Jain - Porwal'},
  {key: 'Jain - Unspecified', value: 'Jain - Unspecified'},
  {key: 'Jain - Vaishya', value: 'Jain - Vaishya'},
  {key: 'Jain - KVO', value: 'Jain - KVO'},
  {key: 'Others', value: 'Others'},
  {key: 'Digambar-Bisapanthi', value: 'Digambar-Bisapanthi'},
  {key: 'Digambar-Gumanapanthi', value: 'Digambar-Gumanapanthi'},
  {key: 'Digambar-Taranapanthi', value: 'Digambar-Taranapanthi'},
  {key: 'Digambar-Terapanthi', value: 'Digambar-Terapanthi'},
  {key: 'Digambar-Totapanthi', value: 'Digambar-Totapanthi'},
  {key: 'Jain - Agarwal', value: 'Jain - Agarwal'},
  {key: 'Jain - Bania', value: 'Jain - Bania'},
  {key: 'Jain - Intercaste', value: 'Jain - Intercaste'},
  {key: 'Jain - Jaiswal', value: 'Jain - Jaiswal'},
  {key: 'Jain - Khandelwal', value: 'Jain - Khandelwal'},
  {key: 'Jain - Kutchi', value: 'Jain - Kutchi'},
  {key: 'Jain - No Bar', value: 'Jain - No Bar'},
  {key: 'Jain - Oswal', value: 'Jain - Oswal'},
  {key: 'Jain - Porwal', value: 'Jain - Porwal'},
  {key: 'Jain - Unspecified', value: 'Jain - Unspecified'},
  {key: 'Jain - Vaishya', value: 'Jain - Vaishya'},
  {key: 'Jain - KVO', value: 'Jain - KVO'},
  {key: 'Others', value: 'Others'},
  {key: 'Shvetambar-Murtipujaka', value: 'Shvetambar-Murtipujaka'},
  {key: 'Shvetambar-Sthanakvasi', value: 'Shvetambar-Sthanakvasi'},
  {key: 'Shvetambar-Terapanthi', value: 'Shvetambar-Terapanthi'},
  {key: 'Jain - Agarwal', value: 'Jain - Agarwal'},
  {key: 'Jain - Bania', value: 'Jain - Bania'},
  {key: 'Jain - Intercaste', value: 'Jain - Intercaste'},
  {key: 'Jain - Jaiswal', value: 'Jain - Jaiswal'},
  {key: 'Jain - Khandelwal', value: 'Jain - Khandelwal'},
  {key: 'Jain - Kutchi', value: 'Jain - Kutchi'},
  {key: 'Jain - No Bar', value: 'Jain - No Bar'},
  {key: 'Jain - Oswal', value: 'Jain - Oswal'},
  {key: 'Jain - Porwal', value: 'Jain - Porwal'},
  {key: 'Jain - Unspecified', value: 'Jain - Unspecified'},
  {key: 'Jain - Vaishya', value: 'Jain - Vaishya'},
  {key: 'Jain - KVO', value: 'Jain - KVO'},
  {key: 'Others', value: 'Others'},
  {key: 'Irani', value: 'Irani'},
  {key: 'Parsi', value: 'Parsi'},
  {key: 'Intercaste', value: 'Intercaste'},
  {key: 'Others', value: 'Others'},
  {key: 'Mahayana', value: 'Mahayana'},
  {key: 'Nichiren Buddhism', value: 'Nichiren Buddhism'},
  {key: 'Pure Land Buddhism', value: 'Pure Land Buddhism'},
  {
    key: 'Tantrayana (Vajrayana Tibetan)',
    value: 'Tantrayana (Vajrayana Tibetan)',
  },
  {key: 'Theravada (Hinayana)', value: 'Theravada (Hinayana)'},
  {
    key: 'Tendai Buddhism (Japanese)',
    value: 'Tendai Buddhism (Japanese)',
  },
  {key: 'Zen Buddhism (China)', value: 'Zen Buddhism (China)'},
  {key: 'Others', value: 'Others'},
  {key: 'Others', value: 'Others'},
  {key: 'Others', value: 'Others'},
  {key: 'Others', value: 'Others'},
];
export const NAKSHTRAM = [
  {key: 'Ashwini', value: 'Ashwini'},
  {key: 'Bharani', value: 'Bharani'},
  {key: 'Krittika', value: 'Krittika'},
  {key: 'Rohini', value: 'Rohini'},
  {key: 'Mrigashira', value: 'Mrigashira'},
  {key: 'Ardra', value: 'Ardra'},
  {key: 'Punarvasu', value: 'Punarvasu'},
  {key: 'Pushya', value: 'Pushya'},
  {key: 'Ashlesha', value: 'Ashlesha'},
  {key: 'Magha', value: 'Magha'},
  {key: 'Purva Phalguni', value: 'Purva Phalguni'},
  {
    key: 'Uttara Phalguni',
    value: 'Uttara Phalguni',
  },
  {key: 'Hasta', value: 'Hasta'},
  {key: 'Chitra', value: 'Chitra'},
  {key: 'Swati', value: 'Swati'},
  {key: 'Vishaka', value: 'Vishaka'},
  {key: 'Anurada', value: 'Anurada'},
  {key: 'Jyeshta', value: 'Jyeshta'},
  {key: 'Mula', value: 'Mula'},
  {key: 'Purva Ashadha', value: 'Purva Ashadha'},
  {key: 'Uttara Ashadha', value: 'Uttara Ashadha'},
  {key: 'Shravana', value: 'Shravana'},
  {key: 'Dhanishta', value: 'Dhanishta'},
  {key: 'Shatabhishak', value: 'Shatabhishak'},
  {
    key: 'Purva Bhadrapada',
    value: 'Purva Bhadrapada',
  },
  {
    key: 'Uttara Bhadrapada',
    value: 'Uttara Bhadrapada',
  },
  {key: 'Revati', value: 'Revati'},
];
export const QUALIFICATION = [
  {
    key: 'Bachelors - Engineering / Computers / Others',
    value: 'Bachelors - Engineering / Computers / Others',
  },
  {
    key: 'Masters - Engineering / Computers / Others',
    value: 'Masters - Engineering / Computers / Others',
  },
  {
    key: 'Bachelors - Arts / Science / Commerce / Others',
    value: 'Bachelors - Arts / Science / Commerce / Others',
  },
  {
    key: 'Masters - Arts / Science / Commerce / Others',
    value: 'Masters - Arts / Science / Commerce / Others',
  },
  {
    key: 'Bachelors - Management / Others',
    value: 'Bachelors - Management / Others',
  },
  {
    key: 'Masters - Management / Others',
    value: 'Masters - Management / Others',
  },
  {
    key: 'Bachelors - Medicine - General / Dental / Surgeon',
    value: 'Bachelors - Medicine - General / Dental / Surgeon',
  },
  {
    key: 'Masters - Medicine - General / Dental / Surgeon',
    value: 'Masters - Medicine - General / Dental / Surgeon',
  },
  {
    key: 'Bachelors - Medicine - Others',
    value: 'Bachelors - Medicine - Others',
  },
  {
    key: 'Masters - Medicine - Others',
    value: 'Masters - Medicine - Others',
  },
  {
    key: 'Bachelors - Legal / Others',
    value: 'Bachelors - Legal / Others',
  },
  {
    key: 'Masters - Legal / Others',
    value: 'Masters - Legal / Others',
  },
  {
    key: 'Finance - ICWAI / CA / CS/ CFA / Others',
    value: 'Finance - ICWAI / CA / CS/ CFA / Others',
  },
  {
    key: 'Service - IAS / IPS / IRS / IES / IFS / Others',
    value: 'Service - IAS / IPS / IRS / IES / IFS / Others',
  },
  {key: 'Doctorates', value: 'Doctorates'},
  {
    key: 'Diploma / Others',
    value: 'Diploma / Others',
  },
  {
    key: 'Higher Secondary / Secondary',
    value: 'Higher Secondary / Secondary',
  },
];
export const STATE = [
  {key: 'Haryana', value: 'Haryana'},
  {key: 'Tamil Nadu', value: 'Tamil Nadu'},
  {key: 'Madhya Pradesh', value: 'Madhya Pradesh'},
  {key: 'Jharkhand', value: 'Jharkhand'},
  {key: 'Mizoram', value: 'Mizoram'},
  {key: 'Nagaland', value: 'Nagaland'},
  {
    key: 'Himachal Pradesh',
    value: 'Himachal Pradesh',
  },
  {key: 'Tripura', value: 'Tripura'},
  {key: 'Andhra Pradesh', value: 'Andhra Pradesh'},
  {key: 'Punjab', value: 'Punjab'},
  {key: 'Chandigarh', value: 'Chandigarh'},
  {key: 'Rajasthan', value: 'Rajasthan'},
  {key: 'Assam', value: 'Assam'},
  {key: 'Odisha', value: 'Odisha'},
  {key: 'Chhattisgarh', value: 'Chhattisgarh'},
  {
    key: 'Jammu and Kashmir',
    value: 'Jammu and Kashmir',
  },
  {key: 'Karnataka', value: 'Karnataka'},
  {key: 'Manipur', value: 'Manipur'},
  {key: 'Kerala', value: 'Kerala'},
  {key: 'Delhi', value: 'Delhi'},
  {
    key: 'Dadra and Nagar Haveli',
    value: 'Dadra and Nagar Haveli',
  },
  {key: 'Puducherry', value: 'Puducherry'},
  {key: 'Uttarakhand', value: 'Uttarakhand'},
  {key: 'Uttar Pradesh', value: 'Uttar Pradesh'},
  {key: 'Bihar', value: 'Bihar'},
  {key: 'Gujarat', value: 'Gujarat'},
  {key: 'Telangana', value: 'Telangana'},
  {key: 'Meghalaya', value: 'Meghalaya'},
  {
    key: 'Himachal Praddesh',
    value: 'Himachal Praddesh',
  },
  {
    key: 'Arunachal Pradesh',
    value: 'Arunachal Pradesh',
  },
  {key: 'Maharashtra', value: 'Maharashtra'},
  {key: 'Goa', value: 'Goa'},
  {key: 'West Bengal', value: 'West Bengal'},
];
export const DISTRICT = [
  {
    state: 'Andhra Pradesh',
    districts: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Nellore',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'Vizianagaram',
      'West Godavari',
      'YSR Kadapa',
    ],
  },
  {
    state: 'Arunachal Pradesh',
    districts: [
      'Tawang',
      'West Kameng',
      'East Kameng',
      'Papum Pare',
      'Kurung Kumey',
      'Kra Daadi',
      'Lower Subansiri',
      'Upper Subansiri',
      'West Siang',
      'East Siang',
      'Siang',
      'Upper Siang',
      'Lower Siang',
      'Lower Dibang Valley',
      'Dibang Valley',
      'Anjaw',
      'Lohit',
      'Namsai',
      'Changlang',
      'Tirap',
      'Longding',
    ],
  },
  {
    state: 'Assam',
    districts: [
      'Baksa',
      'Barpeta',
      'Biswanath',
      'Bongaigaon',
      'Cachar',
      'Charaideo',
      'Chirang',
      'Darrang',
      'Dhemaji',
      'Dhubri',
      'Dibrugarh',
      'Goalpara',
      'Golaghat',
      'Hailakandi',
      'Hojai',
      'Jorhat',
      'Kamrup Metropolitan',
      'Kamrup',
      'Karbi Anglong',
      'Karimganj',
      'Kokrajhar',
      'Lakhimpur',
      'Majuli',
      'Morigaon',
      'Nagaon',
      'Nalbari',
      'Dima Hasao',
      'Sivasagar',
      'Sonitpur',
      'South Salmara-Mankachar',
      'Tinsukia',
      'Udalguri',
      'West Karbi Anglong',
    ],
  },
  {
    state: 'Bihar',
    districts: [
      'Araria',
      'Arwal',
      'Aurangabad',
      'Banka',
      'Begusarai',
      'Bhagalpur',
      'Bhojpur',
      'Buxar',
      'Darbhanga',
      'East Champaran (Motihari)',
      'Gaya',
      'Gopalganj',
      'Jamui',
      'Jehanabad',
      'Kaimur (Bhabua)',
      'Katihar',
      'Khagaria',
      'Kishanganj',
      'Lakhisarai',
      'Madhepura',
      'Madhubani',
      'Munger (Monghyr)',
      'Muzaffarpur',
      'Nalanda',
      'Nawada',
      'Patna',
      'Purnia (Purnea)',
      'Rohtas',
      'Saharsa',
      'Samastipur',
      'Saran',
      'Sheikhpura',
      'Sheohar',
      'Sitamarhi',
      'Siwan',
      'Supaul',
      'Vaishali',
      'West Champaran',
    ],
  },
  {
    state: 'Chandigarh (UT)',
    districts: ['Chandigarh'],
  },
  {
    state: 'Chhattisgarh',
    districts: [
      'Balod',
      'Baloda Bazar',
      'Balrampur',
      'Bastar',
      'Bemetara',
      'Bijapur',
      'Bilaspur',
      'Dantewada (South Bastar)',
      'Dhamtari',
      'Durg',
      'Gariyaband',
      'Janjgir-Champa',
      'Jashpur',
      'Kabirdham (Kawardha)',
      'Kanker (North Bastar)',
      'Kondagaon',
      'Korba',
      'Korea (Koriya)',
      'Mahasamund',
      'Mungeli',
      'Narayanpur',
      'Raigarh',
      'Raipur',
      'Rajnandgaon',
      'Sukma',
      'Surajpur  ',
      'Surguja',
    ],
  },
  {
    state: 'Dadra and Nagar Haveli',
    districts: ['Dadra & Nagar Haveli'],
  },
  {
    state: 'Daman and Diu',
    districts: ['Daman', 'Diu'],
  },
  {
    state: 'Delhi',
    districts: [
      'Central Delhi',
      'East Delhi',
      'New Delhi',
      'North Delhi',
      'North East  Delhi',
      'North West  Delhi',
      'Shahdara',
      'South Delhi',
      'South East Delhi',
      'South West  Delhi',
      'West Delhi',
    ],
  },
  {
    state: 'Goa',
    districts: ['North Goa', 'South Goa'],
  },
  {
    state: 'Gujarat',
    districts: [
      'Ahmedabad',
      'Amreli',
      'Anand',
      'Aravalli',
      'Banaskantha (Palanpur)',
      'Bharuch',
      'Bhavnagar',
      'Botad',
      'Chhota Udepur',
      'Dahod',
      'Dangs (Ahwa)',
      'Devbhoomi Dwarka',
      'Gandhinagar',
      'Gir Somnath',
      'Jamnagar',
      'Junagadh',
      'Kachchh',
      'Kheda (Nadiad)',
      'Mahisagar',
      'Mehsana',
      'Morbi',
      'Narmada (Rajpipla)',
      'Navsari',
      'Panchmahal (Godhra)',
      'Patan',
      'Porbandar',
      'Rajkot',
      'Sabarkantha (Himmatnagar)',
      'Surat',
      'Surendranagar',
      'Tapi (Vyara)',
      'Vadodara',
      'Valsad',
    ],
  },
  {
    state: 'Haryana',
    districts: [
      'Ambala',
      'Bhiwani',
      'Charkhi Dadri',
      'Faridabad',
      'Fatehabad',
      'Gurgaon',
      'Hisar',
      'Jhajjar',
      'Jind',
      'Kaithal',
      'Karnal',
      'Kurukshetra',
      'Mahendragarh',
      'Mewat',
      'Palwal',
      'Panchkula',
      'Panipat',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
      'Yamunanagar',
    ],
  },
  {
    state: 'Himachal Pradesh',
    districts: [
      'Bilaspur',
      'Chamba',
      'Hamirpur',
      'Kangra',
      'Kinnaur',
      'Kullu',
      'Lahaul &amp; Spiti',
      'Mandi',
      'Shimla',
      'Sirmaur (Sirmour)',
      'Solan',
      'Una',
    ],
  },
  {
    state: 'Jammu and Kashmir',
    districts: [
      'Anantnag',
      'Bandipore',
      'Baramulla',
      'Budgam',
      'Doda',
      'Ganderbal',
      'Jammu',
      'Kargil',
      'Kathua',
      'Kishtwar',
      'Kulgam',
      'Kupwara',
      'Leh',
      'Poonch',
      'Pulwama',
      'Rajouri',
      'Ramban',
      'Reasi',
      'Samba',
      'Shopian',
      'Srinagar',
      'Udhampur',
    ],
  },
  {
    state: 'Jharkhand',
    districts: [
      'Bokaro',
      'Chatra',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'East Singhbhum',
      'Garhwa',
      'Giridih',
      'Godda',
      'Gumla',
      'Hazaribag',
      'Jamtara',
      'Khunti',
      'Koderma',
      'Latehar',
      'Lohardaga',
      'Pakur',
      'Palamu',
      'Ramgarh',
      'Ranchi',
      'Sahibganj',
      'Seraikela-Kharsawan',
      'Simdega',
      'West Singhbhum',
    ],
  },
  {
    state: 'Karnataka',
    districts: [
      'Bagalkot',
      'Ballari (Bellary)',
      'Belagavi (Belgaum)',
      'Bengaluru (Bangalore) Rural',
      'Bengaluru (Bangalore) Urban',
      'Bidar',
      'Chamarajanagar',
      'Chikballapur',
      'Chikkamagaluru (Chikmagalur)',
      'Chitradurga',
      'Dakshina Kannada',
      'Davangere',
      'Dharwad',
      'Gadag',
      'Hassan',
      'Haveri',
      'Kalaburagi (Gulbarga)',
      'Kodagu',
      'Kolar',
      'Koppal',
      'Mandya',
      'Mysuru (Mysore)',
      'Raichur',
      'Ramanagara',
      'Shivamogga (Shimoga)',
      'Tumakuru (Tumkur)',
      'Udupi',
      'Uttara Kannada (Karwar)',
      'Vijayapura (Bijapur)',
      'Yadgir',
    ],
  },
  {
    state: 'Kerala',
    districts: [
      'Alappuzha',
      'Ernakulam',
      'Idukki',
      'Kannur',
      'Kasaragod',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Malappuram',
      'Palakkad',
      'Pathanamthitta',
      'Thiruvananthapuram',
      'Thrissur',
      'Wayanad',
    ],
  },
  {
    state: 'Lakshadweep',
    districts: [
      'Agatti',
      'Amini',
      'Androth',
      'Bithra',
      'Chethlath',
      'Kavaratti',
      'Kadmath',
      'Kalpeni',
      'Kilthan',
      'Minicoy',
    ],
  },
  {
    state: 'Madhya Pradesh',
    districts: [
      'Agar Malwa',
      'Alirajpur',
      'Anuppur',
      'Ashoknagar',
      'Balaghat',
      'Barwani',
      'Betul',
      'Bhind',
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Dindori',
      'Guna',
      'Gwalior',
      'Harda',
      'Hoshangabad',
      'Indore',
      'Jabalpur',
      'Jhabua',
      'Katni',
      'Khandwa',
      'Khargone',
      'Mandla',
      'Mandsaur',
      'Morena',
      'Narsinghpur',
      'Neemuch',
      'Panna',
      'Raisen',
      'Rajgarh',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Shajapur',
      'Sheopur',
      'Shivpuri',
      'Sidhi',
      'Singrauli',
      'Tikamgarh',
      'Ujjain',
      'Umaria',
      'Vidisha',
    ],
  },
  {
    state: 'Maharashtra',
    districts: [
      'Ahmednagar',
      'Akola',
      'Amravati',
      'Aurangabad',
      'Beed',
      'Bhandara',
      'Buldhana',
      'Chandrapur',
      'Dhule',
      'Gadchiroli',
      'Gondia',
      'Hingoli',
      'Jalgaon',
      'Jalna',
      'Kolhapur',
      'Latur',
      'Mumbai City',
      'Mumbai Suburban',
      'Nagpur',
      'Nanded',
      'Nandurbar',
      'Nashik',
      'Osmanabad',
      'Palghar',
      'Parbhani',
      'Pune',
      'Raigad',
      'Ratnagiri',
      'Sangli',
      'Satara',
      'Sindhudurg',
      'Solapur',
      'Thane',
      'Wardha',
      'Washim',
      'Yavatmal',
    ],
  },
  {
    state: 'Manipur',
    districts: [
      'Bishnupur',
      'Chandel',
      'Churachandpur',
      'Imphal East',
      'Imphal West',
      'Jiribam',
      'Kakching',
      'Kamjong',
      'Kangpokpi',
      'Noney',
      'Pherzawl',
      'Senapati',
      'Tamenglong',
      'Tengnoupal',
      'Thoubal',
      'Ukhrul',
    ],
  },
  {
    state: 'Meghalaya',
    districts: [
      'East Garo Hills',
      'East Jaintia Hills',
      'East Khasi Hills',
      'North Garo Hills',
      'Ri Bhoi',
      'South Garo Hills',
      'South West Garo Hills ',
      'South West Khasi Hills',
      'West Garo Hills',
      'West Jaintia Hills',
      'West Khasi Hills',
    ],
  },
  {
    state: 'Mizoram',
    districts: [
      'Aizawl',
      'Champhai',
      'Kolasib',
      'Lawngtlai',
      'Lunglei',
      'Mamit',
      'Saiha',
      'Serchhip',
    ],
  },
  {
    state: 'Nagaland',
    districts: [
      'Dimapur',
      'Kiphire',
      'Kohima',
      'Longleng',
      'Mokokchung',
      'Mon',
      'Peren',
      'Phek',
      'Tuensang',
      'Wokha',
      'Zunheboto',
    ],
  },
  {
    state: 'Odisha',
    districts: [
      'Angul',
      'Balangir',
      'Balasore',
      'Bargarh',
      'Bhadrak',
      'Boudh',
      'Cuttack',
      'Deogarh',
      'Dhenkanal',
      'Gajapati',
      'Ganjam',
      'Jagatsinghapur',
      'Jajpur',
      'Jharsuguda',
      'Kalahandi',
      'Kandhamal',
      'Kendrapara',
      'Kendujhar (Keonjhar)',
      'Khordha',
      'Koraput',
      'Malkangiri',
      'Mayurbhanj',
      'Nabarangpur',
      'Nayagarh',
      'Nuapada',
      'Puri',
      'Rayagada',
      'Sambalpur',
      'Sonepur',
      'Sundargarh',
    ],
  },
  {
    state: 'Puducherry',
    districts: ['Karaikal', 'Mahe', 'Pondicherry', 'Yanam'],
  },
  {
    state: 'Punjab',
    districts: [
      'Amritsar',
      'Barnala',
      'Bathinda',
      'Faridkot',
      'Fatehgarh Sahib',
      'Fazilka',
      'Ferozepur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Mansa',
      'Moga',
      'Muktsar',
      'Nawanshahr (Shahid Bhagat Singh Nagar)',
      'Pathankot',
      'Patiala',
      'Rupnagar',
      'Sahibzada Ajit Singh Nagar (Mohali)',
      'Sangrur',
      'Tarn Taran',
    ],
  },
  {
    state: 'Rajasthan',
    districts: [
      'Ajmer',
      'Alwar',
      'Banswara',
      'Baran',
      'Barmer',
      'Bharatpur',
      'Bhilwara',
      'Bikaner',
      'Bundi',
      'Chittorgarh',
      'Churu',
      'Dausa',
      'Dholpur',
      'Dungarpur',
      'Hanumangarh',
      'Jaipur',
      'Jaisalmer',
      'Jalore',
      'Jhalawar',
      'Jhunjhunu',
      'Jodhpur',
      'Karauli',
      'Kota',
      'Nagaur',
      'Pali',
      'Pratapgarh',
      'Rajsamand',
      'Sawai Madhopur',
      'Sikar',
      'Sirohi',
      'Sri Ganganagar',
      'Tonk',
      'Udaipur',
    ],
  },
  {
    state: 'Sikkim',
    districts: ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  },
  {
    state: 'Tamil Nadu',
    districts: [
      'Ariyalur',
      'Chennai',
      'Coimbatore',
      'Cuddalore',
      'Dharmapuri',
      'Dindigul',
      'Erode',
      'Kanchipuram',
      'Kanyakumari',
      'Karur',
      'Krishnagiri',
      'Madurai',
      'Nagapattinam',
      'Namakkal',
      'Nilgiris',
      'Perambalur',
      'Pudukkottai',
      'Ramanathapuram',
      'Salem',
      'Sivaganga',
      'Thanjavur',
      'Theni',
      'Thoothukudi (Tuticorin)',
      'Tiruchirappalli',
      'Tirunelveli',
      'Tiruppur',
      'Tiruvallur',
      'Tiruvannamalai',
      'Tiruvarur',
      'Vellore',
      'Viluppuram',
      'Virudhunagar',
    ],
  },
  {
    state: 'Telangana',
    districts: [
      'Adilabad',
      'Bhadradri Kothagudem',
      'Hyderabad',
      'Jagtial',
      'Jangaon',
      'Jayashankar Bhoopalpally',
      'Jogulamba Gadwal',
      'Kamareddy',
      'Karimnagar',
      'Khammam',
      'Komaram Bheem Asifabad',
      'Mahabubabad',
      'Mahabubnagar',
      'Mancherial',
      'Medak',
      'Medchal',
      'Nagarkurnool',
      'Nalgonda',
      'Nirmal',
      'Nizamabad',
      'Peddapalli',
      'Rajanna Sircilla',
      'Rangareddy',
      'Sangareddy',
      'Siddipet',
      'Suryapet',
      'Vikarabad',
      'Wanaparthy',
      'Warangal (Rural)',
      'Warangal (Urban)',
      'Yadadri Bhuvanagiri',
    ],
  },
  {
    state: 'Tripura',
    districts: [
      'Dhalai',
      'Gomati',
      'Khowai',
      'North Tripura',
      'Sepahijala',
      'South Tripura',
      'Unakoti',
      'West Tripura',
    ],
  },
  {
    state: 'Uttarakhand',
    districts: [
      'Almora',
      'Bageshwar',
      'Chamoli',
      'Champawat',
      'Dehradun',
      'Haridwar',
      'Nainital',
      'Pauri Garhwal',
      'Pithoragarh',
      'Rudraprayag',
      'Tehri Garhwal',
      'Udham Singh Nagar',
      'Uttarkashi',
    ],
  },
  {
    state: 'Uttar Pradesh',
    districts: [
      'Agra',
      'Aligarh',
      'Allahabad',
      'Ambedkar Nagar',
      'Amethi (Chatrapati Sahuji Mahraj Nagar)',
      'Amroha (J.P. Nagar)',
      'Auraiya',
      'Azamgarh',
      'Baghpat',
      'Bahraich',
      'Ballia',
      'Balrampur',
      'Banda',
      'Barabanki',
      'Bareilly',
      'Basti',
      'Bhadohi',
      'Bijnor',
      'Budaun',
      'Bulandshahr',
      'Chandauli',
      'Chitrakoot',
      'Deoria',
      'Etah',
      'Etawah',
      'Faizabad',
      'Farrukhabad',
      'Fatehpur',
      'Firozabad',
      'Gautam Buddha Nagar',
      'Ghaziabad',
      'Ghazipur',
      'Gonda',
      'Gorakhpur',
      'Hamirpur',
      'Hapur (Panchsheel Nagar)',
      'Hardoi',
      'Hathras',
      'Jalaun',
      'Jaunpur',
      'Jhansi',
      'Kannauj',
      'Kanpur Dehat',
      'Kanpur Nagar',
      'Kanshiram Nagar (Kasganj)',
      'Kaushambi',
      'Kushinagar (Padrauna)',
      'Lakhimpur - Kheri',
      'Lalitpur',
      'Lucknow',
      'Maharajganj',
      'Mahoba',
      'Mainpuri',
      'Mathura',
      'Mau',
      'Meerut',
      'Mirzapur',
      'Moradabad',
      'Muzaffarnagar',
      'Pilibhit',
      'Pratapgarh',
      'RaeBareli',
      'Rampur',
      'Saharanpur',
      'Sambhal (Bhim Nagar)',
      'Sant Kabir Nagar',
      'Shahjahanpur',
      'Shamali (Prabuddh Nagar)',
      'Shravasti',
      'Siddharth Nagar',
      'Sitapur',
      'Sonbhadra',
      'Sultanpur',
      'Unnao',
      'Varanasi',
    ],
  },
  {
    state: 'West Bengal',
    districts: [
      'Alipurduar',
      'Bankura',
      'Birbhum',
      'Burdwan (Bardhaman)',
      'Cooch Behar',
      'Dakshin Dinajpur (South Dinajpur)',
      'Darjeeling',
      'Hooghly',
      'Howrah',
      'Jalpaiguri',
      'Kalimpong',
      'Kolkata',
      'Malda',
      'Murshidabad',
      'Nadia',
      'North 24 Parganas',
      'Paschim Medinipur (West Medinipur)',
      'Purba Medinipur (East Medinipur)',
      'Purulia',
      'South 24 Parganas',
      'Uttar Dinajpur (North Dinajpur)',
    ],
  },
];
export const OCCUPATION = [
  {key: 'ADMINISTRATION', value: 'ADMINISTRATION'},
  {key: 'AGRICULTURE', value: 'AGRICULTURE'},
  {key: 'AIRLINE', value: 'AIRLINE'},
  {
    key: 'ARCHITECTURE & DESIGN',
    value: 'ARCHITECTURE & DESIGN',
  },
  {
    key: 'BANKING & FINANCE',
    value: 'BANKING & FINANCE',
  },
  {
    key: 'BEAUTY & FASHION',
    value: 'BEAUTY & FASHION',
  },
  {
    key: 'BPO & CUSTOMER SERVICE',
    value: 'BPO & CUSTOMER SERVICE',
  },
  {key: 'CIVIL SERVICES', value: 'CIVIL SERVICES'},
  {
    key: 'CORPORATE PROFESSIONALS',
    value: 'CORPORATE PROFESSIONALS',
  },
  {key: 'DEFENCE', value: 'DEFENCE'},
  {key: 'DOCTOR', value: 'DOCTOR'},
  {
    key: 'EDUCATION & TRAINING',
    value: 'EDUCATION & TRAINING',
  },
  {key: 'ENGINEERING', value: 'ENGINEERING'},
  {key: 'HOSPITALITY', value: 'HOSPITALITY'},
  {key: 'IT & SOFTWARE', value: 'IT & SOFTWARE'},
  {key: 'LEGAL', value: 'LEGAL'},
  {
    key: 'MEDIA & ENTERTAINMENT',
    value: 'MEDIA & ENTERTAINMENT',
  },
  {
    key: 'MEDICAL & HEALTHCARE - OTHER',
    value: 'MEDICAL & HEALTHCARE - OTHER',
  },
  {key: 'MERCHANT NAVY', value: 'MERCHANT NAVY'},
  {key: 'OTHERS', value: 'OTHERS'},
  {
    key: 'POLICE / LAW ENFORCEMENT',
    value: 'POLICE / LAW ENFORCEMENT',
  },
  {key: 'SCIENTIST', value: 'SCIENTIST'},
  {
    key: 'SENIOR MANAGEMENT',
    value: 'SENIOR MANAGEMENT',
  },
];
export const ANNUAL_INCOME = [
  {key: '0-1 Lakhs', value: '0-1 Lakhs'},
  {key: '1-2 Lakhs', value: '1-2 Lakhs'},
  {key: '2-3 Lakhs', value: '2-3 Lakhs'},
  {key: '3-4 Lakhs', value: '3-4 Lakhs'},
  {key: '4-5 Lakhs', value: '4-5 Lakhs'},
  {key: '5-6 Lakhs', value: '5-6 Lakhs'},
  {key: '6-7 Lakhs', value: '6-7 Lakhs'},
  {key: '7-8 Lakhs', value: '7-8 Lakhs'},
  {key: '8-9 Lakhs', value: '8-9 Lakhs'},
  {key: '9-10 Lakhs', value: '9-10 Lakhs'},
  {key: '10-12 Lakhs', value: '10-12 Lakhs'},
  {key: '12-14 Lakhs', value: '12-14 Lakhs'},
  {key: '14-16 Lakhs', value: '14-16 Lakhs'},
  {key: '16-18 Lakhs', value: '16-18 Lakhs'},
  {key: '18-20 Lakhs', value: '18-20 Lakhs'},
  {key: '20-25 Lakhs', value: '20-25 Lakhs'},
  {key: '25-30 Lakhs', value: '25-30 Lakhs'},
  {key: '30-35 Lakhs', value: '30-35 Lakhs'},
  {key: '35-40 Lakhs', value: '35-40 Lakhs'},
  {key: '40-45 Lakhs', value: '40-45 Lakhs'},
  {key: '45-50 Lakhs', value: '45-50 Lakhs'},
  {key: '50-60 Lakhs', value: '50-60 Lakhs'},
  {key: '60-70 Lakhs', value: '60-70 Lakhs'},
  {key: '70-80 Lakhs', value: '70-80 Lakhs'},
  {key: '80-90 Lakhs', value: '80-90 Lakhs'},
  {
    key: '90 Lakhs- 1 Crore',
    value: '90 Lakhs- 1 Crore',
  },
  {
    key: '1 Crore & Above',
    value: '1 Crore & Above',
  },
];
export const COUNTRY = [
  {key: 'United States', value: 'United States'},
  {key: 'Canada', value: 'Canada'},
  {key: 'Afghanistan', value: 'Afghanistan'},
  {key: 'Albania', value: 'Albania'},
  {key: 'Algeria', value: 'Algeria'},
  {key: 'American Samoa', value: 'American Samoa'},
  {key: 'Andorra', value: 'Andorra'},
  {key: 'Angola', value: 'Angola'},
  {key: 'Anguilla', value: 'Anguilla'},
  {key: 'Antarctica', value: 'Antarctica'},
  {
    key: 'Antigua and/or Barbuda',
    value: 'Antigua and/or Barbuda',
  },
  {key: 'Argentina', value: 'Argentina'},
  {key: 'Armenia', value: 'Armenia'},
  {key: 'Aruba', value: 'Aruba'},
  {key: 'Australia', value: 'Australia'},
  {key: 'Austria', value: 'Austria'},
  {key: 'Azerbaijan', value: 'Azerbaijan'},
  {key: 'Bahamas', value: 'Bahamas'},
  {key: 'Bahrain', value: 'Bahrain'},
  {key: 'Bangladesh', value: 'Bangladesh'},
  {key: 'Barbados', value: 'Barbados'},
  {key: 'Belarus', value: 'Belarus'},
  {key: 'Belgium', value: 'Belgium'},
  {key: 'Belize', value: 'Belize'},
  {key: 'Benin', value: 'Benin'},
  {key: 'Bermuda', value: 'Bermuda'},
  {key: 'Bhutan', value: 'Bhutan'},
  {key: 'Bolivia', value: 'Bolivia'},
  {
    key: 'Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
  },
  {key: 'Botswana', value: 'Botswana'},
  {key: 'Bouvet Island', value: 'Bouvet Island'},
  {key: 'Brazil', value: 'Brazil'},
  {
    key: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  },
  {
    key: 'Brunei Darussalam',
    value: 'Brunei Darussalam',
  },
  {key: 'Bulgaria', value: 'Bulgaria'},
  {key: 'Burkina Faso', value: 'Burkina Faso'},
  {key: 'Burundi', value: 'Burundi'},
  {key: 'Cambodia', value: 'Cambodia'},
  {key: 'Cameroon', value: 'Cameroon'},
  {key: 'Cape Verde', value: 'Cape Verde'},
  {key: 'Cayman Islands', value: 'Cayman Islands'},
  {
    key: 'Central African Republic',
    value: 'Central African Republic',
  },
  {key: 'Chad', value: 'Chad'},
  {key: 'Chile', value: 'Chile'},
  {key: 'China', value: 'China'},
  {
    key: 'Christmas Island',
    value: 'Christmas Island',
  },
  {
    key: 'Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
  },
  {key: 'Colombia', value: 'Colombia'},
  {key: 'Comoros', value: 'Comoros'},
  {key: 'Congo', value: 'Congo'},
  {key: 'Cook Islands', value: 'Cook Islands'},
  {key: 'Costa Rica', value: 'Costa Rica'},
  {
    key: 'Croatia (Hrvatska)',
    value: 'Croatia (Hrvatska)',
  },
  {key: 'Cuba', value: 'Cuba'},
  {key: 'Cyprus', value: 'Cyprus'},
  {key: 'Czech Republic', value: 'Czech Republic'},
  {key: 'Denmark', value: 'Denmark'},
  {key: 'Djibouti', value: 'Djibouti'},
  {key: 'Dominica', value: 'Dominica'},
  {
    key: 'Dominican Republic',
    value: 'Dominican Republic',
  },
  {key: 'East Timor', value: 'East Timor'},
  {key: 'Ecudaor', value: 'Ecudaor'},
  {key: 'Egypt', value: 'Egypt'},
  {key: 'El Salvador', value: 'El Salvador'},
  {
    key: 'Equatorial Guinea',
    value: 'Equatorial Guinea',
  },
  {key: 'Eritrea', value: 'Eritrea'},
  {key: 'Estonia', value: 'Estonia'},
  {key: 'Ethiopia', value: 'Ethiopia'},
  {
    key: 'Falkland Islands (Malvinas)',
    value: 'Falkland Islands (Malvinas)',
  },
  {key: 'Faroe Islands', value: 'Faroe Islands'},
  {key: 'Fiji', value: 'Fiji'},
  {key: 'Finland', value: 'Finland'},
  {key: 'France', value: 'France'},
  {
    key: 'France, Metropolitan',
    value: 'France, Metropolitan',
  },
  {key: 'French Guiana', value: 'French Guiana'},
  {
    key: 'French Polynesia',
    value: 'French Polynesia',
  },
  {
    key: 'French Southern Territories',
    value: 'French Southern Territories',
  },
  {key: 'Gabon', value: 'Gabon'},
  {key: 'Gambia', value: 'Gambia'},
  {key: 'Georgia', value: 'Georgia'},
  {key: 'Germany', value: 'Germany'},
  {key: 'Ghana', value: 'Ghana'},
  {key: 'Gibraltar', value: 'Gibraltar'},
  {key: 'Greece', value: 'Greece'},
  {key: 'Greenland', value: 'Greenland'},
  {key: 'Grenada', value: 'Grenada'},
  {key: 'Guadeloupe', value: 'Guadeloupe'},
  {key: 'Guam', value: 'Guam'},
  {key: 'Guatemala', value: 'Guatemala'},
  {key: 'Guinea', value: 'Guinea'},
  {key: 'Guinea-Bissau', value: 'Guinea-Bissau'},
  {key: 'Guyana', value: 'Guyana'},
  {key: 'Haiti', value: 'Haiti'},
  {
    key: 'Heard and Mc Donald Islands',
    value: 'Heard and Mc Donald Islands',
  },
  {key: 'Honduras', value: 'Honduras'},
  {key: 'Hong Kong', value: 'Hong Kong'},
  {key: 'Hungary', value: 'Hungary'},
  {key: 'Iceland', value: 'Iceland'},
  {key: 'India', value: 'India'},
  {key: 'Indonesia', value: 'Indonesia'},
  {
    key: 'Iran (Islamic Republic of)',
    value: 'Iran (Islamic Republic of)',
  },
  {key: 'Iraq', value: 'Iraq'},
  {key: 'Ireland', value: 'Ireland'},
  {key: 'Israel', value: 'Israel'},
  {key: 'Italy', value: 'Italy'},
  {key: 'Ivory Coast', value: 'Ivory Coast'},
  {key: 'Jamaica', value: 'Jamaica'},
  {key: 'Japan', value: 'Japan'},
  {key: 'Jordan', value: 'Jordan'},
  {key: 'Kazakhstan', value: 'Kazakhstan'},
  {key: 'Kenya', value: 'Kenya'},
  {key: 'Kiribati', value: 'Kiribati'},
  {
    key: "Korea, Democratic People's Republic of",
    value: "Korea, Democratic People's Republic of",
  },
  {
    key: 'Korea, Republic of',
    value: 'Korea, Republic of',
  },
  {key: 'Kosovo', value: 'Kosovo'},
  {key: 'Kuwait', value: 'Kuwait'},
  {key: 'Kyrgyzstan', value: 'Kyrgyzstan'},
  {
    key: "Lao People's Democratic Republic",
    value: "Lao People's Democratic Republic",
  },
  {key: 'Latvia', value: 'Latvia'},
  {key: 'Lebanon', value: 'Lebanon'},
  {key: 'Lesotho', value: 'Lesotho'},
  {key: 'Liberia', value: 'Liberia'},
  {key: 'Libyan Arab Jamahiriya', value: 'Libyan Arab Jamahiriya'},
  {key: 'Liechtenstein', value: 'Liechtenstein'},
  {key: 'Lithuania', value: 'Lithuania'},
  {key: 'Luxembourg', value: 'Luxembourg'},
  {key: 'Macau', value: 'Macau'},
  {key: 'Macedonia', value: 'Macedonia'},
  {key: 'Madagascar', value: 'Madagascar'},
  {key: 'Malawi', value: 'Malawi'},
  {key: 'Malaysia', value: 'Malaysia'},
  {key: 'Maldives', value: 'Maldives'},
  {key: 'Mali', value: 'Mali'},
  {key: 'Malta', value: 'Malta'},
  {
    key: 'Marshall Islands',
    value: 'Marshall Islands',
  },
  {key: 'Martinique', value: 'Martinique'},
  {key: 'Mauritania', value: 'Mauritania'},
  {key: 'Mauritius', value: 'Mauritius'},
  {key: 'Mayotte', value: 'Mayotte'},
  {key: 'Mexico', value: 'Mexico'},
  {
    key: 'Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
  },
  {
    key: 'Moldova, Republic of',
    value: 'Moldova, Republic of',
  },
  {key: 'Monaco', value: 'Monaco'},
  {key: 'Mongolia', value: 'Mongolia'},
  {key: 'Montserrat', value: 'Montserrat'},
  {key: 'Morocco', value: 'Morocco'},
  {key: 'Mozambique', value: 'Mozambique'},
  {key: 'Myanmar', value: 'Myanmar'},
  {key: 'Namibia', value: 'Namibia'},
  {key: 'Nauru', value: 'Nauru'},
  {key: 'Nepal', value: 'Nepal'},
  {key: 'Netherlands', value: 'Netherlands'},
  {
    key: 'Netherlands Antilles',
    value: 'Netherlands Antilles',
  },
  {key: 'New Caledonia', value: 'New Caledonia'},
  {key: 'New Zealand', value: 'New Zealand'},
  {key: 'Nicaragua', value: 'Nicaragua'},
  {key: 'Niger', value: 'Niger'},
  {key: 'Nigeria', value: 'Nigeria'},
  {key: 'Niue', value: 'Niue'},
  {key: 'Norfork Island', value: 'Norfork Island'},
  {
    key: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
  },
  {key: 'Norway', value: 'Norway'},
  {key: 'Oman', value: 'Oman'},
  {key: 'Pakistan', value: 'Pakistan'},
  {key: 'Palau', value: 'Palau'},
  {key: 'Panama', value: 'Panama'},
  {
    key: 'Papua New Guinea',
    value: 'Papua New Guinea',
  },
  {key: 'Paraguay', value: 'Paraguay'},
  {key: 'Peru', value: 'Peru'},
  {key: 'Philippines', value: 'Philippines'},
  {key: 'Pitcairn', value: 'Pitcairn'},
  {key: 'Poland', value: 'Poland'},
  {key: 'Portugal', value: 'Portugal'},
  {key: 'Puerto Rico', value: 'Puerto Rico'},
  {key: 'Qatar', value: 'Qatar'},
  {key: 'Reunion', value: 'Reunion'},
  {key: 'Romania', value: 'Romania'},
  {
    key: 'Russian Federation',
    value: 'Russian Federation',
  },
  {key: 'Rwanda', value: 'Rwanda'},
  {
    key: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
  },
  {key: 'Saint Lucia', value: 'Saint Lucia'},
  {
    key: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  {key: 'Samoa', value: 'Samoa'},
  {key: 'San Marino', value: 'San Marino'},
  {
    key: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
  },
  {key: 'Saudi Arabia', value: 'Saudi Arabia'},
  {key: 'Senegal', value: 'Senegal'},
  {key: 'Seychelles', value: 'Seychelles'},
  {key: 'Sierra Leone', value: 'Sierra Leone'},
  {key: 'Singapore', value: 'Singapore'},
  {key: 'Slovakia', value: 'Slovakia'},
  {key: 'Slovenia', value: 'Slovenia'},
  {
    key: 'Solomon Islands',
    value: 'Solomon Islands',
  },
  {key: 'Somalia', value: 'Somalia'},
  {key: 'South Africa', value: 'South Africa'},
  {
    key: 'South Georgia South Sandwich Islands',
    value: 'South Georgia South Sandwich Islands',
  },
  {key: 'South Sudan', value: 'South Sudan'},
  {key: 'Spain', value: 'Spain'},
  {key: 'Sri Lanka', value: 'Sri Lanka'},
  {key: 'St. Helena', value: 'St. Helena'},
  {
    key: 'St. Pierre and Miquelon',
    value: 'St. Pierre and Miquelon',
  },
  {key: 'Sudan', value: 'Sudan'},
  {key: 'Suriname', value: 'Suriname'},
  {
    key: 'Svalbarn and Jan Mayen Islands',
    value: 'Svalbarn and Jan Mayen Islands',
  },
  {key: 'Swaziland', value: 'Swaziland'},
  {key: 'Sweden', value: 'Sweden'},
  {key: 'Switzerland', value: 'Switzerland'},
  {
    key: 'Syrian Arab Republic',
    value: 'Syrian Arab Republic',
  },
  {key: 'Taiwan', value: 'Taiwan'},
  {key: 'Tajikistan', value: 'Tajikistan'},
  {
    key: 'Tanzania, United Republic of',
    value: 'Tanzania, United Republic of',
  },
  {key: 'Thailand', value: 'Thailand'},
  {key: 'Togo', value: 'Togo'},
  {key: 'Tokelau', value: 'Tokelau'},
  {key: 'Tonga', value: 'Tonga'},
  {
    key: 'Trinidad and Tobago',
    value: 'Trinidad and Tobago',
  },
  {key: 'Tunisia', value: 'Tunisia'},
  {key: 'Turkey', value: 'Turkey'},
  {key: 'Turkmenistan', value: 'Turkmenistan'},
  {
    key: 'Turks and Caicos Islands',
    value: 'Turks and Caicos Islands',
  },
  {key: 'Tuvalu', value: 'Tuvalu'},
  {key: 'Uganda', value: 'Uganda'},
  {key: 'Ukraine', value: 'Ukraine'},
  {
    key: 'United Arab Emirates',
    value: 'United Arab Emirates',
  },
  {key: 'United Kingdom', value: 'United Kingdom'},
  {
    key: 'United States minor outlying islands',
    value: 'United States minor outlying islands',
  },
  {key: 'Uruguay', value: 'Uruguay'},
  {key: 'Uzbekistan', value: 'Uzbekistan'},
  {key: 'Vanuatu', value: 'Vanuatu'},
  {
    key: 'Vatican City State',
    value: 'Vatican City State',
  },
  {key: 'Venezuela', value: 'Venezuela'},
  {key: 'Vietnam', value: 'Vietnam'},
  {
    key: 'Virigan Islands (British)',
    value: 'Virigan Islands (British)',
  },
  {
    key: 'Virgin Islands (U.S.)',
    value: 'Virgin Islands (U.S.)',
  },
  {
    key: 'Wallis and Futuna Islands',
    value: 'Wallis and Futuna Islands',
  },
  {key: 'Western Sahara', value: 'Western Sahara'},
  {key: 'Yemen', value: 'Yemen'},
  {key: 'Yugoslavia', value: 'Yugoslavia'},
  {key: 'Zaire', value: 'Zaire'},
  {key: 'Zambia', value: 'Zambia'},
  {key: 'Zimbabwe', value: 'Zimbabwe'},
];
