export const DAILY_RECOMMENDATIONS = 'DAILY_RECOMMENDATIONS';

export const HOROSCOPIC_MATCHES = 'HOROSCOPIC_MATCHES';

export const PREFERENCE_MATCHES = 'PREFERENCE_MATCHES';
export const AUTH_FAIL = 'AUTH_FAIL';
